# Generated by Django 2.1.1 on 2018-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='state',
            field=models.CharField(choices=[('archived', 'ARCHIVE_TASK'), ('pinned', 'PIN_TASK'), ('active', 'ACTIVE_TASK')], default='active', max_length=6),
        ),
    ]
