# Generated by Django 2.1.1 on 2018-09-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20180909_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.CharField(choices=[('archived', 'archived'), ('pinned', 'pinned'), ('active', 'active')], default='active', max_length=8),
        ),
    ]
