# Generated by Django 2.1.1 on 2018-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20180909_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='pin',
            field=models.CharField(choices=[('default', 'default'), ('pinned', 'pinned')], default='default', max_length=7),
        ),
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived')], default='active', max_length=8),
        ),
    ]
